from .personales import Personales
from .cuenta import Cuenta
from .metricas import Metricas
from .domicilio import Domicilio
from .usuario import Usuario
from .clase import Clase
from .horario import Horario
from .paquete import Paquete
from .subscripcion import Subscripcion
from .casillahorario import Casillahorario
from .historial import Historial
from .curso import Curso