name: proyecto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  provider: ^6.1.4
  file_picker: ^10.1.9
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^5.0.1
  sqflite_common_ffi: ^2.3.5
  path_provider: ^2.1.5
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: ['assets/']
