from .usuario_schema import UsuarioSchema
from .cuenta_schema import CuentaSchema
from .personales_schema import PersonalesSchema
from .metricas_schema import MetricasSchema
from .domicilio_schema import DomicilioSchema
from .paquete_schema import PaqueteSchema
from .subscripcion_schema import SubscripcionSchema
from .horario_schema import HorarioSchema
from .casillahorario_schema import CasillahorarioSchema
from .clase_schema import ClaseSchema
from .historial_schema import HistorialSchema
from .curso_schema import CursoSchema